### PR TITLE
Build system substitution and simplified debianization

### PR DESCRIPTION
**Pull request by vitalyisaev2**
@netheril96 first we would like to thank you for a nice work you performed with this library. Some of our Linux-based solutions rely on it, so we would like to make the use of it a bit more standardized. At the moment our projects acquire ```autojsoncxx``` as a git submodule, but it's not very convenient due to the absence of of version control which is preferable for our build system. That's why we would like to have packages and we ask you to consider merging this PR. 

**New features**:
1. Changed build system from raw ```Makefile``` files to ```CMake```;
2. Added opportunity to build binary ```deb``` packages with ```CPack```.

Since this project doesn't provide information about versions, but Debian packaging system requires the one, I've assigned [```0.1.0```](https://github.com/vitalyisaev2/autojsoncxx/blob/master/CMakeLists.txt#L6) version to them. I also use build date to mark the package. Please feel free to change it in the way you like.

See the content of the package below:
```bash
$ dpkg -c autojsoncxx_0.1.0~git20150420-1_all-dev.deb
drwxr-xr-x root/root         0 2015-04-20 11:58 ./usr/
drwxr-xr-x root/root         0 2015-04-20 11:58 ./usr/include/
drwxr-xr-x root/root         0 2015-04-20 11:58 ./usr/include/autojsoncxx/
-rw-r--r-- root/root     12334 2015-04-20 11:57 ./usr/include/autojsoncxx/utility.hpp
-rw-r--r-- root/root     12425 2015-04-20 11:57 ./usr/include/autojsoncxx/boost_types.hpp
-rw-r--r-- root/root      3453 2015-04-20 11:57 ./usr/include/autojsoncxx/from_json.hpp
-rw-r--r-- root/root      4546 2015-04-20 11:57 ./usr/include/autojsoncxx/to_json.hpp
-rw-r--r-- root/root      1627 2015-04-20 11:57 ./usr/include/autojsoncxx/autojsoncxx.hpp
-rw-r--r-- root/root     11594 2015-04-20 11:57 ./usr/include/autojsoncxx/map_types.hpp
-rw-r--r-- root/root      8556 2015-04-20 11:57 ./usr/include/autojsoncxx/tuple_types.hpp
-rw-r--r-- root/root      6986 2015-04-20 11:57 ./usr/include/autojsoncxx/dom.hpp
-rw-r--r-- root/root     10419 2015-04-20 11:57 ./usr/include/autojsoncxx/array_types.hpp
-rw-r--r-- root/root     16833 2015-04-20 11:57 ./usr/include/autojsoncxx/error.hpp
-rw-r--r-- root/root     11613 2015-04-20 11:57 ./usr/include/autojsoncxx/base.hpp
-rw-r--r-- root/root      6601 2015-04-20 11:57 ./usr/include/autojsoncxx/nullable_types.hpp
drwxr-xr-x root/root         0 2015-04-20 11:58 ./usr/bin/
-rwxr-xr-x root/root     18441 2015-04-20 11:57 ./usr/bin/autojsoncxx.py
drwxr-xr-x root/root         0 2015-04-20 11:58 ./usr/share/
-rwxr-xr-x root/root      7099 2015-04-20 11:57 ./usr/share/code_template
```

### CODE REVIEW

**Comment by netheril96** [comment]
Thanks for your PR. I am delighted to see my code actually benefiting other people.

CMake is a good idea, but given it is cross platform, it is best that we can unify the Windows build into CMake as well.

I don't understand the point of binary deb package, though. This project is header-only except for the test part.

About the version number, in the `release` section there are several versions, the most recent one being 0.3.0. I haven't thought about the version for the HEAD now.

I will test your PR later when I have access to Windows and Linux.

**Comment by vitalyisaev2** [comment]
@netheril96 thank you for a prompt reply. I've updated the library version. 

In Debian (and RHEL, for all i know) headers are distributed with  ```*-dev```/```*-devel``` binary packages, as well as compiled binaries itself. It's a common practice. 

Regarding Windows, unfortunately I'm not aware of Windows installers...

**Comment by netheril96** [comment]
@vitalyisaev2 

About Windows, I was talking about building the test with CMake.

A suggestion: search for python in `$PATH` rather than hard-code `/usr/bin/python`. And if your package is based on the HEAD commit rather than the one tagged with `v0.3.0`, the version should be a bit different. Maybe 0.3.1.

Another question, given that I am not familiar with CMake and CPack. How does this installation handle the dependency `rapidjson`? There is a chance that `autojsoncxx` may break when `rapidjson` is updated, which happened once before.

**Comment by vitalyisaev2** [comment]
@netheril96 

Since I'm not a Windows user, I can't suggest how much effort should be made to build test examples on that system. I've wrapped the python interpreter select line in OS-aware conditions (just ```python``` from ```$PATH``` didn't work for me), but I'm not sure if that's enough. I have not even a Windows VM on-the-go at the moment...

Versioning can become "semiautomatic" due to git tag integration, but it's not supported by CMake and will require custom CMake extensions as dependencies of your project (see [this article](http://ipenguin.ws/2012/11/cmake-automatically-use-git-tags-as.html)). 

The dependency problem you described is serious but there is no opportunity to resolve it in a good way. There are no ```RapidJSON``` packages in any of the Linux distributions, as well as there is no changelog in the project repository. If we have your dependencies packaged, we'd just put the build deps version restrictions in your main ```CMakeLists.txt``` and thus prevent the most of the build problems. But now we can only rely on the tests performed before build. ```RapidJSON``` leader told that he's going to fix this issues after v1.0.

This patch will allow your users (like me) to control the state of your library and own projects dependent on yours, build ```deb``` packages and store it in own repositories for the further use in build process.

**Pull request merged**
