### PR TITLE
Staticjson

### PR DESCRIPTION
**Pull request by netheril96**
Rewrite

### CODE REVIEW

**Comment by vitalyisaev2** [comment]
Our build infrastructure significantly relies on C++ code generation performed by ```autojsoncxx.py``` script. Unfortunately this merge breaks all the legacy code we have, so we have stay on the previous version :(

**Comment by gggin** [comment]
same with @vitalyisaev2 
why not support both?

**Comment by netheril96** [comment]
@vitalyisaev2  @gggin How about a rewritten `autojsoncxx.py` that generates C++ code compatible with the new model? I can also add a compatibility header so that old namespace and class names can be used.

**Comment by netheril96** [comment]
The new version removes some support for more advanced types. I've branched off the original version in a new branch `autojsoncxx` and will try to backport some bug fixes onto it.

**Comment by gggin** [comment]
It sounds like so great!

**Pull request merged**
