### PR TITLE
Fix search path for code_template

### PR DESCRIPTION
**Pull request by vitalyisaev2**
I've noticed that ```autojsoncxx.py``` is looking for a ```code_template``` in the same directory where it's situated (for both Windows and Linux). But package now installs ```code_template``` into the ```share``` destination, according to Linux conventions. So now I've added an additional path for Linux systems (```/usr/share/autojsoncxx/```). On Windows the behavior of ```autojsoncxx.py``` remains the same.

### CODE REVIEW

**Comment by netheril96** [comment]
OK, I did not anticipate such problems. Adding `/usr/share/autojsoncxx` (shouldn't it be `/usr/local/share/autojsoncxx` instead?) is an ad hoc solution. I am currently thinking about two possible solutions:

1. A more general search. Starting from an environment variable `AUTOJSONCXX_TEMPLATE_DIR`, then `/usr/local/share/autojsoncxx`,  `/usr/share/autojsoncxx`, at last the script directory.
2. Given how deeply coupled the script and template file are, maybe they should be merged together. This also solves the path search when user specify a different install prefix than `/usr/local`.

**Comment by vitalyisaev2** [comment]
In case of Windows, everything hopefully remains the same - both ```code_template``` and ```autojsoncxx.py``` are going to the CMake's ```bin``` destination. 

On the Linux now we have several options (in decreasing order of priority):
1. ```AUTOJSONCXX_TEMPLATE_DIR``` (if set and it's value refers to existing folder);
2. ```/usr/local/share/autojsoncxx``` for those who use ```make install```;
3. ```/usr/local/autojsoncxx``` for those who use ```deb``` binary;
4. ```os.path.dirname(os.path.abspath(__file__))``` to make the tests work.

Regarding the merging executable and template, you mean including ```code_template``` text as a big multiline sting in ```autojsoncxx.py```?

**Comment by netheril96** [comment]
@vitalyisaev2 

> Regarding the merging executable and template, you mean including code_template text as a big multiline sting in autojsoncxx.py?

Yes. The template and code generator are heavily coupled; one cannot be changed without the other being changed as well. They were separated for ease of development, but now that they are mostly stable, perhaps they should be merged to ease deployment instead.

Are you aware of any downsides of doing so? For example, maybe the python interpreter would be slowed down much by such a big string literal.

**Comment by vitalyisaev2** [comment]
@netheril96 Hello, I'm very sorry for a delay with reply. From my point of view storing code with data is not a very a good practice nowadays. But since we have troubles with distribution of ```code_template```, we (probably) should merge these files. Also we should take into account the situation if someone will need to modify ```code_template``` or use several differing ```code_template```s on the one's system. Is it possible?

**Comment by netheril96** [comment]
@vitalyisaev2 

After some thought, I decided to abandon the merger. It is not a good engineering design.

**Pull request merged**
